name: Build

on:
  push:
    branches:
      - main
      - develop
      - "release/**"
      - "hotfix/**"
      - "feature/**"
    paths-ignore:
      - "README.md"
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    #todo: what is the equivalent of appveyors "skip_branch_with_pr: true" ?
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0
      - name: Cache Tools
        uses: actions/cache@v2
        with:
          path: tools
          key: ${{ runner.os }}-tools-${{ hashFiles('recipe.cake') }}
      - name: Build project
        uses: cake-build/cake-action@v1
        with:
          script-path: recipe.cake
          target: CI
          verbosity: Diagnostic
          cake-version: 0.38.4
          cake-bootstrap: true
      - name: Upload Issues
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: warn
          name: ${{ matrix.os }} Issues
          path: |
            BuildArtifacts/report.html
            BuildArtifacts/**/coverlet/*.xml
      - name: Upload Packages
        uses: actions/upload-artifact@v2
        if: matrix.os == 'windows-latest'
        with:
          if-no-files-found: warn
          name: package
          path: BuildArtifacts/Packages/**/*